language: python

python:
  - "3.7"

env:
  - NUMPY_VERSION=1.18
    SCIPY_VERSION=1.4

before_install:
  - pip install numpy==$NUMPY_VERSION

install:
  - python setup.py develop

before_script:
  - pip	install	pytest
  - pip	install	pytest-cov
  - pip install scipy==$SCIPY_VERSION

script:
  - pytest -v tests/ --cov=exampy/