language: python

python:
  - "3.8"
  - "3.7"

env:
  - NUMPY_VERSION=1.18
  - NUMPY_VERSION=1.17
  - NUMPY_VERSION=1.16

matrix:
  exclude:
    - python: "3.8"
      env: NUMPY_VERSION=1.17
    - python: "3.8"
      env: NUMPY_VERSION=1.16

before_install:
  - pip install numpy==$NUMPY_VERSION

install:
  - python setup.py develop

before_script:
  - pip	install	pytest
  - pip	install	pytest-cov
  - pip install scipy

script:
  - pytest -v tests/ --cov=exampy/
