language: python

python:
  - "3.8"
  - "3.7"

env:
  - NUMPY_VERSION=1.18.1
  - NUMPY_VERSION=1.17.4
  - NUMPY_VERSION=1.16.6

matrix:
  include:
    - python: "3.6"
      env: NUMPY_VERSION=1.18.1

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda config --add channels conda-forge
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION "numpy==$NUMPY_VERSION" scipy pip
  - source activate test-environment

install:
  - python setup.py develop

before_script:
  - pip	install	pytest
  - pip	install	pytest-cov

script:
  - pytest -v tests/ --cov=exampy/

notifications:
  email:
    recipients:
      - bovy@astro.utoronto.ca
    on_success: change
    on_failure: change
